In [1]:
using BenchmarkTools

In [108]:
include("src/TypedPolynomials.jl")
t = TypedPolynomials

TypedPolynomials

In [109]:
t.@polyvar x y z

z

In [110]:
p = t.Polynomial(x)

x

In [111]:
typeof(promote(p, y))

Tuple{TypedPolynomials.Polynomial{TypedPolynomials.Term{Int64,TypedPolynomials.Monomial{2,(y, x)}},StaticArrays.SVector{1,TypedPolynomials.Term{Int64,TypedPolynomials.Monomial{2,(y, x)}}}},TypedPolynomials.Polynomial{TypedPolynomials.Term{Int64,TypedPolynomials.Monomial{2,(y, x)}},StaticArrays.SVector{1,TypedPolynomials.Term{Int64,TypedPolynomials.Monomial{2,(y, x)}}}}}

In [107]:
@code_warntype promote(p, y)
@benchmark promote($p, $y)

Variables:
  #self#::Base.#promote
  x::TypedPolynomials.Polynomial{TypedPolynomials.Term{Int64,TypedPolynomials.Monomial{1,(x,)}},StaticArrays.SVector{1,TypedPolynomials.Term{Int64,TypedPolynomials.Monomial{1,(x,)}}}}
  y::TypedPolynomials.Variable{:y}

Body:
  begin 
      $(Expr(:inbounds, false))
      # meta: location /Users/rdeits/.julia/v0.6/TypedPolynomials/src/TypedPolynomials.jl convert 92
      # meta: location /Users/rdeits/.julia/v0.6/StaticArrays/src/core.jl convert 69
      # meta: location /Users/rdeits/.julia/v0.6/StaticArrays/src/SVector.jl Type 24
      # meta: location /Users/rdeits/.julia/v0.6/StaticArrays/src/util.jl convert_ntuple 8
      # meta: location /Users/rdeits/.julia/v0.6/StaticArrays/src/util.jl # line 11:
      SSAValue(3) = (Base.getfield)((Core.getfield)((Core.getfield)(x::TypedPolynomials.Polynomial{TypedPolynomials.Term{Int64,TypedPolynomials.Monomial{1,(x,)}},StaticArrays.SVector{1,TypedPolynomials.Term{Int64,TypedPolynomials.Monomial{1,(x,)}}}}, 

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     2.260 ns (0.00% GC)
  median time:      2.264 ns (0.00% GC)
  mean time:        2.562 ns (0.00% GC)
  maximum time:     14.063 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%

In [92]:
promote(x, y)

(x, y)

In [93]:
promote(p, y)

(x, y)

In [70]:
promote(x, 2y)

(x, 2y)

In [71]:
promote(3x, 2y)

(3x, 2y)

In [33]:
@which promote(x, 2y)

promote(x::T, y::S) where {T, S} in Base at promotion.jl:174

In [32]:
t1, t2 = promote(x, 2y)

(1, 2)

In [23]:
t.variables(t1.monomial)

(y, x)

In [24]:
t1.monomial.exponents

(0, 0)

In [20]:
typeof(promote(x, 2y))

Tuple{TypedPolynomials.Term{Int64,TypedPolynomials.Monomial{2,(y, x)}},TypedPolynomials.Term{Int64,TypedPolynomials.Monomial{2,(y, x)}}}

In [4]:
promote(x, y)

(x, y)

In [5]:
typeof(promote(x, y))

Tuple{TypedPolynomials.Monomial{2,(x, y)},TypedPolynomials.Monomial{2,(x, y)}}

In [6]:
convert(t.Monomial{2, (x, y)}, y)

y

In [122]:
@code_warntype t.Monomial(x)

Variables:
  #self#::Any
  v::TypedPolynomials.Variable{:x}

Body:
  begin 
      return $(Expr(:new, :($(QuoteNode(TypedPolynomials.Monomial{1,(x,)}))), :((Core.tuple)(1)::Tuple{Int64})))
  end::TypedPolynomials.Monomial{1,(x,)}


In [98]:
promote(x, y)

(x, y)

In [68]:
promote_type(typeof(x), typeof(y))

TypedPolynomials.Monomial{2,(x, y)}

In [71]:
typeof(convert(t.Monomial{2, (x, y)}, x))

TypedPolynomials.Monomial{1,(x,)}

In [72]:
?findfirst

search: findfirst



```
findfirst(A)
```

Return the linear index of the first non-zero value in `A` (determined by `A[i]!=0`). Returns `0` if no such value is found.

```jldoctest
julia> A = [0 0; 1 0]
2×2 Array{Int64,2}:
 0  0
 1  0

julia> findfirst(A)
2
```

```
findfirst(A, v)
```

Return the linear index of the first element equal to `v` in `A`. Returns `0` if `v` is not found.

```jldoctest
julia> A = [4 6; 2 2]
2×2 Array{Int64,2}:
 4  6
 2  2

julia> findfirst(A,2)
2

julia> findfirst(A,3)
0
```

```
findfirst(predicate::Function, A)
```

Return the linear index of the first element of `A` for which `predicate` returns `true`. Returns `0` if there is no such element.

```jldoctest
julia> A = [1 4; 2 2]
2×2 Array{Int64,2}:
 1  4
 2  2

julia> findfirst(iseven, A)
2

julia> findfirst(x -> x>10, A)
0
```


In [69]:
@which promote(x, y)

promote(x::T, y::S) where {T, S} in Base at promotion.jl:174

In [67]:
typeof(promote(x, y))

Tuple{TypedPolynomials.Monomial{1,(x,)},TypedPolynomials.Monomial{1,(y,)}}

In [28]:
f(x) = x^2 + x

f (generic function with 2 methods)

In [29]:
f(x) = @allocated x^2 + x

f (generic function with 2 methods)

In [46]:
vcat((1,), (2,))

2-element Array{Tuple{Int64},1}:
 (1,)
 (2,)

In [ ]:
searchsorted

In [31]:
f(x)

192

In [32]:

function testmonomials(var, degree)
    [var^i for i in 0:degree]
end

testmonomials (generic function with 1 method)

In [35]:
f(x) = @allocated testmonomials(x, 3)

f (generic function with 2 methods)

In [37]:
f(x)

112

In [40]:
(f(x) - sizeof(Int)) / 4

26.0

In [41]:
sizeof(x^2)

8

In [43]:
sizeof(eltype(testmonomials(x, 3)))

8

sizeof(Int)

@allocated f(x)

In [17]:
begin
    function f(x)
        t.@polyvar x
        x^2
    end
    @allocated f()
end

0

In [16]:
@allocated f()

0

In [10]:
@allocated x^2

16

In [99]:
x + 1

1 + x

In [100]:
p = x^2 + y

y + x^2

In [101]:
x^2 + 2x + 1

1 + 2x + x^2

In [102]:
p = x^2 * y + y^2 + x

x + y^2 + x^2y

In [103]:
p(x=>4)

4 + 16y + y^2

In [104]:
t.subs(p, x=>z)

z + y^2 + yz^2

In [105]:
p = x^2 + y + x * x + 3 * x * y + x * y^2

y + 3xy + 2x^2 + xy^2

In [106]:
[x^i for i in 0:3]

4-element Array{IJulia.TypedPolynomials.Monomial{1,(x,)},1}:
 1  
 x  
 x^2
 x^3

In [107]:
m1 = x^2
m2 = x * y

xy

In [108]:
m1 < m2

false

In [109]:
@code_warntype Base.isless(m1, m2)

Variables:
  #self#::Base.#isless
  m1::IJulia.TypedPolynomials.Monomial{1,(x,)}
  m2::IJulia.TypedPolynomials.Monomial{2,(x, y)}

Body:
  begin 
      $(Expr(:inbounds, false))
      # meta: location promotion.jl promote 174
      # meta: location /Users/rdeits/.julia/v0.6/TypedPolynomials/src/TypedPolynomials.jl convert 96
      # meta: location /Users/rdeits/.julia/v0.6/TypedPolynomials/src/TypedPolynomials.jl # line 107:
      SSAValue(1) = $(Expr(:new, :($(QuoteNode(IJulia.TypedPolynomials.Monomial{2,(x, y)}))), :((Core.tuple)((Base.getfield)((Core.getfield)(m1, :exponents)::Tuple{Int64}, 1)::Int64, 0)::Tuple{Int64,Int64})))
      # meta: pop location
      # meta: pop location
      # meta: location /Users/rdeits/.julia/v0.6/TypedPolynomials/src/TypedPolynomials.jl convert 96
      # meta: location /Users/rdeits/.julia/v0.6/TypedPolynomials/src/TypedPolynomials.jl # line 107:
      SSAValue(0) = $(Expr(:new, :($(QuoteNode(IJulia.TypedPolynomials.Monomial{2,(x, y)}))), :((Core.tup

In [110]:
@benchmark Base.isless($m1, $m2)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     4.221 ns (0.00% GC)
  median time:      4.340 ns (0.00% GC)
  mean time:        4.793 ns (0.00% GC)
  maximum time:     26.204 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%

In [111]:
@benchmark $x^2 + $y + $x * $x + 3 * $x * $y + $x * $y^2

BenchmarkTools.Trial: 
  memory estimate:  720 bytes
  allocs estimate:  8
  --------------
  minimum time:     309.714 ns (0.00% GC)
  median time:      342.588 ns (0.00% GC)
  mean time:        426.022 ns (14.01% GC)
  maximum time:     12.636 μs (91.31% GC)
  --------------
  samples:          10000
  evals/sample:     255
  time tolerance:   5.00%
  memory tolerance: 1.00%

In [112]:
@benchmark $x^2 + $y

BenchmarkTools.Trial: 
  memory estimate:  208 bytes
  allocs estimate:  4
  --------------
  minimum time:     69.877 ns (0.00% GC)
  median time:      74.264 ns (0.00% GC)
  mean time:        104.470 ns (23.98% GC)
  maximum time:     5.101 μs (93.32% GC)
  --------------
  samples:          10000
  evals/sample:     976
  time tolerance:   5.00%
  memory tolerance: 1.00%